services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  link-service:
    build:
      context: ..
      dockerfile: src/link-service/deploy/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      LINK_FORGE_REDIS: redis
      LINK_FORGE_DOMAIN: lit.by
      SPRING_RABBITMQ_HOST: broker
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: password
    depends_on:
      redis:
        condition: service_healthy
      broker:
        condition: service_healthy

  tracking-service:
    build:
      context: ..
      dockerfile: src/tracking-service/deploy/Dockerfile
    environment:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: broker
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: password
    depends_on:
      redis:
        condition: service_healthy
      broker:
        condition: service_healthy

  broker:
    image:
      rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
  rabbitmq_data:
